#!/bin/sh

GITIT=gitit

case $1 in
	start)
		echo "Starting gitit wiki"
		$GITIT -f wiki.conf &
	;;
	stop)
		echo "Stoping gitit wiki"
		killall $GITIT
	;;
	restart)
		echo "Restarting gitit wiki"
		killall $GITIT
		$GITIT -f wiki.conf &
	;;
	*)
		echo "Use 'start' or 'stop'"
	;;
esac

