#!/bin/sh

GITIT=gitit
BASEDIR=`dirname $0`

case $1 in
	start)
		echo "Starting gitit wiki..."
		cd $BASEDIR
		$GITIT -f wiki.conf >/dev/null &
		echo $! > wiki.pid
	;;
	stop)
		echo "Stoping gitit wiki..."
		cd $BASEDIR
		kill `cat wiki.pid 2>/dev/null` 2>/dev/null && rm wiki.pid || echo "Cannot stop!"
	;;
	restart)
		cd $BASEDIR
		./wiki stop
		./wiki start
	;;
	*)
		echo "Use 'start', 'stop', or 'restart'"
	;;
esac

