<div id="footer" class="container">
		<ul>
				$if(feed)$
				<li>
						<a href="$base$/_feed/" type="application/atom+xml" rel="alternate" title="ATOM Feed">
						訂閱 (Atom) <img alt="feed icon" src="$base$/img/icons/feed.png"/>
						</a>
				</li>
				$endif$
				<li><a href="$base$/Help">說明</a></li>
				<li>Powered by <a href="http://github.com/jgm/gitit/tree/master/">gitit</a></li>
				<li>Customized by CrBoy</li>
		</ul>
</div>
