<div id="footer" class="container">
	<div id="license">
		<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/tw/deed.zh_TW"><img alt="創用 CC 授權條款" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/tw/88x31.png" /></a><br />本站所有內容，除另有標註外，採用<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/tw/deed.zh_TW">創用 CC 姓名標示-相同方式分享 3.0 台灣 授權條款</a>授權
	</div>
	<ul>
		$if(feed)$
		<li>
			<a href="$base$/_feed/" type="application/atom+xml" rel="alternate" title="ATOM Feed">
			訂閱 (Atom) <img alt="feed icon" src="$base$/img/icons/feed.png"/>
			</a>
		</li>
		$endif$
		<li><a href="$base$/Help">說明</a></li>
		<li>Powered by <a href="http://github.com/jgm/gitit/tree/master/">gitit</a></li>
		<li>Customized by CrBoy</li>
	</ul>
</div>
