
<link href='http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.css' type='text/css' rel='stylesheet' />
<script type='text/javascript' src='http://google-code-prettify.googlecode.com/svn/trunk/src/prettify.js'></script>
<script>
	var pres = document.getElementsByTagName('pre');
	for (i=0; i<pres.length; i++){
		var e = pres[i];
		e.className = 'prettyprint';
	}
	prettyPrint();
</script>
