<div id="socialshare" style="float:right">
		<!--<input type="button" onclick="javascript: void(window.open('http://www.plurk.com/?qualifier=shares&status=[推] '.concat(encodeURIComponent(location.href)).concat(' ').concat('(').concat(encodeURIComponent(document.title)).concat(')')));" value="推到Plurk" /> 
		<input type="button" onclick="javascript: void(window.open('http://twitter.com/home/?status='.concat(encodeURIComponent(document.title)).concat(' ').concat(encodeURIComponent(location.href))));" value="推到Twitter" />
		<input type="button" onclick="javascript: void(window.open('http://www.facebook.com/share.php?u='.concat(encodeURIComponent(location.href))));" value="推到Facebook" />-->
		<a href="#" onclick="javascript: void(window.open('http://www.plurk.com/?qualifier=shares&status=[推] '.concat(encodeURIComponent(location.href)).concat(' ').concat('(').concat(encodeURIComponent(document.title)).concat(')')));"><img src="$base$/img/icons/plurk.png" alt="分享到plurk" style="width: 2em;"></a>
		<a href="#" onclick="javascript: void(window.open('http://twitter.com/home/?status='.concat(encodeURIComponent(document.title)).concat(' ').concat(encodeURIComponent(location.href))));"><img src="$base$/img/icons/twitter.png" alt="分享到twitter" style="width: 2em;"></a>
		<a href="#" onclick="javascript: void(window.open('http://www.facebook.com/share.php?u='.concat(encodeURIComponent(location.href))));" ><img src="$base$/img/icons/facebook.png" alt="分享到facebook" style="width: 2em;"></a>
</div>
